### ISSUE TITLE
Computed property macros

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#392] opened 2016-10-27 14:13 UTC
`ember-i18n` has a `translationMacro`, which essentially generates a computed property listening to `i18n.locale` (see https://github.com/jamesarosen/ember-i18n/blob/master/addon/utils/macro.js). Would something like that be desirable in `ember-intl` too?

**Comment by jasonmit** [comment] 2016-10-27 18:35
No but I'll happily add this as I want feature parity between the two libs

**Comment by jasonmit** [comment] 2016-10-28 06:30
this is included within 2.15.0

**Comment by Turbo87** [comment] 2016-10-28 08:11
since `ember-intl` has a larger API surface (`formatNumber/Date/Time()`) we could also offer those as macros, right?

**Comment by jasonmit** [comment] 2016-10-28 08:31
I'll happily support that.

What do you think of an API like:

```js
import formatNumber from 'ember-intl';
export default Ember.Object.extend({
  intl: injectService(),

  cost: formatNumer('model.price', {
    dependentKeys: ['session.user.currency'],
    options() {
      return {
        style: 'currency',
        currency: get(this, 'session.user.currency')
      };
    }
  }
});
```

**Comment by Turbo87** [comment] 2016-10-28 09:03
I hadn't thought about passing options, but that's a good point. We might be able to simplify the API a bit though. How about something like this:

```
import { formatNumber, fromComputed } from 'ember-intl';

export default Ember.Controller.extend({
  intl: injectService(),
  currency: 'USD',

  cost: formatNumer('model.price', {
    style: 'currency',
    currency: fromComputed('currency'),
  }),
});
```

the `fromComputed()` function would essentially just wrap the string and mark it as a dependency key instead of a literal value.

/cc @kellyselden @marcoow any comments on such a proposal?

**Comment by marcoow** [comment] 2016-10-28 09:07
@Turbo87: would it make sense to require `currency` to be a property name so that you can get rid of `fromComputed`?

**Comment by Turbo87** [comment] 2016-10-28 09:24
I'm not sure. There might be legitimate use cases for `currency` being a static string. also `style` being static and `currency` dynamic would probably confuse people.

**Comment by marcoow** [comment] 2016-10-28 09:43
Yeah, good point. I just feel that `fromComputed` adds complexity to the API that could potentially be prevented

**Comment by Turbo87** [comment] 2016-10-28 09:51
```js
  currency: key`some-key`
```

might also work, but I'm not sure if that's really an improvement...

I guess the issue is that we can't be sure that the options will always be computed or always be static. We need *something* to mark the key as static/dynamic.

**Comment by marcoow** [comment] 2016-10-28 09:53
Could also check at runtime whether a property exists with that name 😱

**Comment by jasonmit** [comment] 2016-10-28 18:55
@marcoow that can conflict, so I'd prefer either a wrapper to signify literal v. path or my original syntax.

https://github.com/emberjs/ember.js/pull/4185 I wish this had landed

**Comment by kellyselden** [comment] 2016-10-28 19:05
> emberjs/ember.js#4185 I wish this had landed

It lives on in https://github.com/kellyselden/ember-awesome-macros. I didn't like how ember-cpm would look up a string as a property on your component first, and if not there, use as a value. It is bug prone in my opinion/collisions. The API I use is if it is a string, look up the property on the object, if you want to use the string as a value, you must escape via `raw('my value')`. I hope this helps the discussion and is not off topic.

**Comment by jasonmit** [comment] 2016-10-28 22:32
@kellyselden would you be open to me extracting `raw` into a standalone addon?

**Comment by kellyselden** [comment] 2016-10-28 22:35
Oh boy, it may overkill to addonify `raw`. It is so tiny: https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/raw.js

```js
export default function(key) {
  return computed(() => key);
}
```

**Comment by jasonmit** [comment] 2016-10-28 22:39
I was thinking more for standardizing around a module that works across libs that have complex computed macros

**Comment by kellyselden** [comment] 2016-10-28 22:47
> I was thinking more for standardizing around a module that works across libs that have complex computed macros

Oh that makes more sense 😄. Yeah I would be interested in exploring that. We both could then just re-export it.

**Comment by Turbo87** [comment] 2016-10-31 09:11
I tend to prefer using something like `fromComputed()` instead of `raw()`, i.e. marking something as a key instead of marking it as a literal. Reason for that is that it would be easier to copy-paste code from normal invocations of the service function to the computed macro. Then again if such a large addon is already using `raw()` it might make more sense to standardize on that.

One thing I don't like about the `raw()` implementation above is that it creates an unnecessary computed property and from what I've heard computed properties are quite a bit more expensive than a static property.

What I would imagine is the `raw()` function just wrapping the string in an object with `raw: true` in it and the computed property macros then look for the `raw` property and use either static string inside or make it a proper dependency.

**Comment by jasonmit** [comment] 2016-11-01 00:35
> I tend to prefer using something like fromComputed() instead of raw(), i.e. marking something as a key instead of marking it as a literal. Reason for that is that it would be easier to copy-paste code from normal invocations of the service function to the computed macro. Then again if such a large addon is already using raw() it might make more sense to standardize on that.

Most (maybe all?) of the baked in computed deal with path keys whenever a string is involved so I think we should continue with that.  If a literal is intended, I'd prefer `literal(value)`.

> One thing I don't like about the raw() implementation above is that it creates an unnecessary computed property and from what I've heard computed properties are quite a bit more expensive than a static property.

I'm fine with making it a constructor and check the instance type versus a computed.  Any objections @kellyselden ?

I'll likely start on this tonight or tomorrow.

**Comment by Turbo87** [comment] 2016-11-01 00:55
the difference to the baked in macros is that we are talking about values in an options object, not plain parameters of the macro itself.

**Comment by jasonmit** [comment] 2016-11-01 01:05
> the difference to the baked in macros is that we are talking about values in an options object, not plain parameters of the macro itself.

Fair point.  And the more I think about this the more the public API begins to even confuse myself (even when taking into consideration fromComputed/raw/literal wrappers).

I may end up going back to my original idea with a slight tweak in passing the computed's "owner" into the options fn as an argument.  I feel any sort of clever thing will only lead to confusion or deficiencies in the API.

```js
cost: formatNumer('model.price', {
  dependentKeys: ['currency'],
  options(owner) {
    return {
      style: 'currency',
      currency: get(owner, 'currency')
    };
  }
})
```

Yeah, it's slightly more typing but I think the intended behavior is clear versus raw/literal wrapping and/or changing the context of the options fn to be the owner of the computed.

**Comment by Turbo87** [comment] 2016-11-01 14:52
> Fair point. And the more I think about this the more the public API begins to even confuse myself (even when taking into consideration fromComputed/raw/literal wrappers).

yeah, the built-ins are not that perfect either unfortunately.

> I may end up going back to my original idea with a slight tweak in passing the computed's "owner" into the options fn as an argument. I feel any sort of clever solution may lead to confusion or deficiencies in the API.

hmm, that would be unfortunate. I think we were on a good track with `raw()` or `fromComputed()` or something like that.

**Comment by marcoow** [comment] 2016-11-02 09:07
@Turbo87: isn't the problem with this:

```es6
cost: formatNumer('model.price', {
  style: 'currency',
  currency: fromComputed('currency'),
}),
```

that `fromComputed` cannot add `currency` as a dependent key to the `cost` property but that `formatNumer` would have to check whether `currency` is a CP or a value?

**Comment by Turbo87** [comment] 2016-11-02 09:22
> that fromComputed cannot add currency as a dependent key to the cost property but that formatNumer would have to check whether currency is a CP or a value?

to be honest, I don't see this as a problem.

```js
function ref(key) {
  return { key, isReference: true };
}

dependencies = Object.keys(options)
  .map(key => options[key])
  .filter(value => value.isReference)
  .map(it => it.key);
```

> Whereas with sth. like raw we could simply assume that everything is a CP and might change, making a type check unnecessary.

that is true, but then you have the overhead of using computed properties for everything, and I'm not sure if that overhead is actually smaller than the `ref()` wrapper and type check above.

**Comment by marcoow** [comment] 2016-11-02 09:28
I don't think there's a lot of overhead with using properties for static values as `get` would simply read the prop from the instance and the dependency wouldn't hurt as well when the property is actually static.

I'm more concerned about adding a bunch of complexity in order to be able to support both static values and properties (which might be CPs) at the same time. This isn't really specific to ember-intl of course but more a general issue. Accepting either static values or properties as arguments are really 2 different things semantically and I'm note sure it's worth the effort to try and make them more or less interchangeable.

**Comment by Turbo87** [comment] 2016-11-02 09:33
I've updated the above code sample with an actual implementation. It doesn't seem that complex to me, but maybe I'm missing something...

(I haven't tested the code, but something roughly like that should work. It also only works for shallow objects, but that is all we need here.)

**Comment by marcoow** [comment] 2016-11-02 09:35
My point is more that you'll have to add that handling for arguments either being static values or properties to all these macros now whereas if you simply define the API so that particular arguments are either expected to be static values or property names you don't.

**Comment by Turbo87** [comment] 2016-11-02 09:39
> My point is more that you'll have to add that handling for arguments either being static values or properties to all these macros now whereas if you simply define the API so that particular arguments are either expected to be static values or property names you don't.

that's obviously correct. but as you can see in the code example above it can be reduced down to just two additional lines and I'm not even sure if "additional" is correct here, since you would need those line or roughly similar lines anyway as soon as you're handling property refs in any way, whether optional or not.

**Comment by marcoow** [comment] 2016-11-02 11:48
I see what you mean. I'm just not sure whether being able to accept property names and values as arguments is sth. that's valuable at all really. I find allowing both

```es6
{
  cost: formatNumer('model.price', {
    style: 'currency',
    currency: ref('currency'),
  }),

  currency: 'USD'
}
```

and

```es6
{
  cost: formatNumer('model.price', {
    style: 'currency',
    currency: 'USD'
  })
}
```

conceptually more complex than requiring that arg (in this case `currency`) is a property name

```es6
{
  cost: formatNumer('model.price', {
    style: 'currency',
    currency: 'currency'
  }),

  currency: 'USD'
}
```

**Comment by Turbo87** [comment] 2016-11-02 13:23
> requiring that arg (in this case `currency`) is a property name

my problem with that is that you need to read the documentation to understand which options are static and which are dynamic, while in the other case it's obvious by looking at the code. you could obviously require *all* options to be references, but that would get ugly pretty fast if you're formatting multiple numbers with different options.

**Comment by marcoow** [comment] 2016-11-02 13:27
Right - seems both alternatives aren't really ideal

**Comment by buschtoens** [comment] 2018-10-20 10:55
By now we have released https://github.com/ember-intl/ember-intl/pull/626, which adds a [`raw` function](https://github.com/kellyselden/ember-macro-helpers#raw) like in [`ember-awesome-macros`](https://github.com/kellyselden/ember-awesome-macros) / [`ember-macro-helpers`](https://github.com/kellyselden/ember-macro-helpers).

In the almost two years that have passed since the last comment to this discussion, also quite a lot in Ember itself has changed. The community is now migrating towards ES6 classes and decorators, which we now also support: [`@ember-intl/decorators`](https://github.com/ember-intl/decorators)

I also would like to throw in my two cents here. The `translationMacro` / `@t` decorator is together with the `raw` function and the fact that we now auto-lookup the `intl` service (https://github.com/ember-intl/ember-intl/pull/614) quite useful and terse:

```ts
import Component from '@ember/component';
import { t, raw } from '@ember-intl/decorators';

class ExampleComponent extends Component {
  name = 'Tom';

  @t('messages.welcome', {
    firstName: 'name',
    lastName: raw('Dale')
  })
  message!: string;
}
```

`raw` was a good choice for `@t`, because it's (at least in my experience) more likely to pass dynamic variables.

For `formatNumber` and `formatDate` this is true for the actual value, but usually not the case for the config parameters, except maybe `currency`, so that this API might be more desirable:

```ts
import Component from '@ember/component';
import { formatNumber, raw, dynamic } from '@ember-intl/decorators';

class ExampleComponent extends Component {
  value = 1.23;
  currency = 'EUR';

  @formatNumber('value', {
    style: 'currency',
    currency: dynamic('currency')
  })
  dynamicFormattedValue!: string;

  @formatNumber(raw(4.56), {
    style: 'currency',
    currency: dynamic('currency')
  })
  staticFormattedValue!: string;
}
```

We might also make the `raw` optional for all `@formatX` helpers, since they all expect non-string values.

```ts
import Component from '@ember/component';
import { formatNumber, dynamic } from '@ember-intl/decorators';

class ExampleComponent extends Component {
  value = 1.23;
  currency = 'EUR';

  @formatNumber('value', {
    style: 'currency',
    currency: dynamic('currency')
  })
  dynamicFormattedValue!: string;

  @formatNumber(4.56, {
    style: 'currency',
    currency: dynamic('currency')
  })
  staticFormattedValue!: string;
}
```

But tbh, all this seems quite complicated to me and is a lot of extra cognitive load. I was toying around with different ideas and would be interested in your opinions

```ts
import Component from '@ember/component';
import { intl } from '@ember-intl/decorators';

class ExampleComponent extends Component {
  value = 1.23;
  currency = 'EUR';

  @intl('value', 'currency')
  dynamicFormattedValue = intl => intl.formatNumber(
    this.value,
    { style: 'currency', currency: this.currency }
  );

  @intl('currency')
  staticFormattedValue = intl => intl.formatNumber(
    4.56,
    { style: 'currency', currency: this.currency }
  );
}
```

`@intl` would create a computed property that calls the function with the `intl` service and uses all of the passed parameters as dependent keys. It also recomputed, when the `intl.locale` changes (https://github.com/ember-intl/ember-intl/issues/636).

**Comment by buschtoens** [comment] 2018-10-20 10:59
Alternative suggestion that uses less syntax, but is also less clear / intuitive to me.

```ts
import Component from '@ember/component';
import { formatNumber } from '@ember-intl/decorators';

class ExampleComponent extends Component {
  value = 1.23;
  currency = 'EUR';

  @formatNumber('value', 'currency')
  dynamicFormattedValue = [
    this.value,
    { style: 'currency', currency: this.currency }
  ];

  @formatNumber('currency')
  staticFormattedValue = [
    4.56,
    { style: 'currency', currency: this.currency }
  };
}
```

**Comment by buschtoens** [comment] 2018-11-28 11:40
I've implemented the suggested `@intl` decorator in https://github.com/ember-intl/decorators/pull/66.

**Closed** 2018-11-29 09:16 UTC
Labels: enhancement
