### ISSUE TITLE
The release of 4.3.1 should have been a major change

### ISSUE THREAD

**Issue by mansona** [ember-intl/ember-intl#1248] opened 2020-04-20 10:46 UTC
Hey folks 👋 

I know that the "bug" that was fixed in 4.3.1 would suggest that it should be a patch release, because it can change the behaviour of the host app it really should have been a 5.0 release 🙈 Any app that was (accidentally) relying on this config will now break when updating a patch release for ember-intl

**Comment by Turbo87** [comment] 2020-04-20 10:52
FWIW I tend to agree with @jasonmit that this is a bug fix. Yes, in some cases it might break apps, but only because those apps have neglected to configure their auto-import correctly. That misconfiguration is most likely caused by this bug existing in ember-intl, but I still don't think that this bugfix would need a major version release. What would have been nice though is mentioning this more explicitly in a changelog.

**Comment by mansona** [comment] 2020-04-20 11:01
The reason why this is so problematic is that the time you should "configure your auto-import correctly" is when you're adding a third party node package that relies on the particular Node globals definitions. 

Having defaults like this change in a patch release of an unrelated package will cause a lot of problems for teams or developers that aren't aware of the specific auto-import/webpack issue that causes these problems.

**Comment by jasonmit** [comment] 2020-04-20 18:37
Closing in favor of https://github.com/ember-intl/ember-intl/issues/1232

It was an actual bug as it was breaking fastboot for some.  If it were harmless I would entertain keeping it around for the sake of apps that rely on global but have not configured ember-auto-import.

**Closed by jasonmit** 2020-04-20 18:37 UTC

**Comment by jasonmit** [comment] 2020-04-20 18:42
Also this upstream change landed in a minor version of ember auto import: https://github.com/ef4/ember-auto-import/pull/216/ which set this chain of events off.

**Comment by jasonmit** [comment] 2020-04-20 21:29
@Turbo87 I don't keep a CHANGELOG because I find them to be a bit redundant and often times missing information.  I simply don't have a process I like for keeping a CHANGELOG running and trustworthy.  I updated the [release notes of 4.3.1](https://github.com/ember-intl/ember-intl/releases/tag/v4.3.1) to add context re: this issue.  For the time being, I recommend diffing release tags to see what changed.

**Comment by Turbo87** [comment] 2020-04-21 06:00
I can recommend using https://github.com/lerna/lerna-changelog to automatically generate the changelog based on merged and labeled PRs
