### ISSUE TITLE
Abbreviated numbers (enhancement)

### ISSUE THREAD

**Issue by doublex** [ember-intl/ember-intl#589] opened 2018-06-26 20:31 UTC
CLDR supports in "numbers" -&gt; "decimalFormats" -&gt; "decimalFormat" abbreviated numbers, .e.g.:
3150 -> "3k"
700000000 -> "700M"
Would be a great enhancement.

**Comment by jasonmit** [comment] 2018-06-26 21:30
Dupe of https://github.com/ember-intl/ember-intl/issues/66

**Closed by jasonmit** 2018-06-26 21:30 UTC
