### ISSUE TITLE
v5.7.0 to v6.0.0 migration: Assertion failed error

### ISSUE THREAD

**Issue by francispeixoto** [ember-intl/ember-intl#1611] opened 2021-11-04 20:26 UTC
- [X ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [ X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.28.3
- Ember CLI Version: 3.28.3
- Ember Intl Version: 6.0.0
- Browser(s): Chrome 93.0
- Node Version: 14.7.6

### Steps to Reproduce

- Update ember-intl from 5.7.0 t0 6.0.0 via npm
- ember test

```
not ok 1 Chrome 93.0 - [131 ms] - Integration | Component | navbar: it renders

    ---

        stack: >

            Error: Assertion Failed: You attempted to update '_locale' on '<(unknown):ember171>', but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

            '_locale' was first used:
            
            - While rendering:
              -top-level
                application
                  index
                    navbar
                      bs-navbar
                        bs-navbar/content
                          bs-collapse
                            bs-navbar/nav
                              bs-nav/item
                                bs-navbar/link-to
                                  bs-link-to
                                    link-to
            
            Stack trace for the update:
                at dirtyTagFor (http://localhost:7357/assets/vendor.js:58515:37)
                at setter (http://localhost:7357/assets/vendor.js:58801:7)
                at _class2.set [as _locale] (http://localhost:7357/assets/vendor.js:16458:7)
                at _class2.set locale [as locale] (http://localhost:7357/assets/vendor.js:121125:22)
                at _class2.setLocale (http://localhost:7357/assets/vendor.js:121351:19)
                at new _class2 (http://localhost:7357/assets/vendor.js:121182:12)
                at Function.create (http://localhost:7357/assets/vendor.js:29497:20)
        message: >
            global failure: Error: Assertion Failed: You attempted to update `_locale` on `<(unknown):ember171>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
            
            `_locale` was first used:
            
            - While rendering:
              -top-level
                application
                  index
                    navbar
                      bs-navbar
                        bs-navbar/content
                          bs-collapse
                            bs-navbar/nav
                              bs-nav/item
                                bs-navbar/link-to
                                  bs-link-to
                                    link-to
            
            Stack trace for the update:
        negative: >
            false
        browser log: |
            {"type":"warn","text":"DEPRECATION: Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities. [deprecation id: manager-capabilities.modifiers-3-13] See https://deprecations.emberjs.com/v3.x#toc_manager-capabilities-modifiers-3-13 for more details.\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:36565:21)\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:36698:9)\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:36592:9)\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:36698:9)\n        at http://localhost:7357/assets/test-support.js:6638:10\n        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:36698:9)\n        at invoke (http://localhost:7357/assets/vendor.js:36710:9)\n        at deprecate (http://localhost:7357/assets/vendor.js:36666:28)\n        at modifierCapabilities$1 (http://localhost:7357/assets/vendor.js:11683:62)"}
            {"type":"error","text":"\n\nError occurred:\n\n- While rendering:\n  -top-level\n    application\n      index\n        navbar\n          bs-navbar\n            bs-navbar/content\n              bs-collapse\n                bs-navbar/nav\n                  bs-nav/item\n                    bs-navbar/link-to\n                      bs-link-to\n                        link-to\n\n"}
            {"type":"error","text":"\n\nError occurred:\n\n\n\n"}
    ...
```

**Comment by charlesfries** [comment] 2021-11-05 21:12
I'm also seeing this issue after upgrading in an existing app. What's interesting is that I don't see the error with a simple reproduction:

`ember new intl-repro && cd intl-repro && ember install ember-intl && ember s`

Produces no errors:

```
DEBUG: -------------------------------
DEBUG: Ember      : 3.28.6
DEBUG: Ember Data : 3.28.3
DEBUG: -------------------------------
```

Produces an error:

```
DEBUG: -------------------------------
DEBUG: Ember                 : 3.28.6
DEBUG: Ember Data            : 3.27.1
DEBUG: Ember Model Validator : 3.10.0
DEBUG: Model Fragments       : 5.0.0-beta.2
DEBUG: -------------------------------
```

**Comment by francispeixoto** [comment] 2021-11-06 13:38
so it seems that earlier versions of intl inject something that 6.0.0 can't digest. i tried to look for the _locale reference in my code but i couldn't find it. might need to trace in the module itself.

**Comment by charlesfries** [comment] 2021-11-06 20:51
Does this trace help?

![Screenshot 2021-11-06 135048](https://user-images.githubusercontent.com/2275005/140623452-56628c20-d5ee-44cd-a3e8-ff425c9e02a0.png)
![Screenshot 2021-11-06 135027](https://user-images.githubusercontent.com/2275005/140623453-eaff1e2a-4994-48d7-91f3-661bce7fae97.png)
![Screenshot 2021-11-06 135101](https://user-images.githubusercontent.com/2275005/140623454-861cffba-6689-4aef-9607-07ca4cf89d0e.png)

**Comment by charlesfries** [comment] 2021-11-06 21:13
Figured it out. We need to call `setLocale` before any templates are rendered, a good place is probably the `ApplicationRoute` constructor. This is still probably an issue that needs resolving, though.

```js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class ApplicationRoute extends Route {
  @service intl;

  constructor() {
    super(...arguments);

    this.intl.setLocale('en-us');
  }
}
```

**Comment by xomaczar** [comment] 2021-11-09 15:39
I am also seeing this failure but only tests. Adding `setupIntl(hooks)` to a given test module resolves the issue for me.

**Comment by jrjohnson** [comment] 2021-11-12 17:57
I have the same result as @xomaczar, I'm not sure if this is a new requirement because some injector has been removed or if it's a bug in the add-on though.

**Comment by nadnoslen** [comment] 2021-11-12 22:22
This problem manifested itself in a number of my integration tests that previous to ember-intl@v6 managed to format without me explicitly setting the locale.  Not certain how this worked in v5 and earlier, but that's not something I care to worry about.

To fix my problem, I had to set the the locale (using intl's test helper `setLocale`) before several of my integration tests that indirectly depended on `Intl` formatting and translations.

So ...

```js
// ...
import { setLocale } from 'ember-intl/test-support';
// ...

module('Integration | Component | some-sort/of-test', function (hooks) {
  setupRenderingTest(hooks);

  hooks.beforeEach(() => setLocale('en'));  // in my case I default to 'en', yours might be 'en-us' or 'fr-ca' ... whatevs
}

**Comment by stopfstedt** [comment] 2021-11-17 20:40
adding `setupIntl` to your integration tests (where missing) resolved this problem for us.

https://ember-intl.github.io/ember-intl/versions/master/docs/guide/testing#setupintl-hooks-locale-translations-

**Comment by francispeixoto** [comment] 2021-11-17 20:46
This means the helper isn't a helper anymore, it's almost a prerequisite. and depending on how your compontents are built and called, it might have to part of almost every integration test.

**Comment by stopfstedt** [comment] 2021-11-17 21:36
> It might have to part of almost every integration test.

@francispeixoto I'd say give it a try and add `setupIntl` to your integration tests before throwing them out altogether.

here's a commit for an example that set things right for me today:
https://github.com/ilios/common/commit/9a2ab6aa05e8d89c2014640ffdc72b570141a41d

i hope this works for you too!

**Comment by charlesfries** [comment] 2021-11-17 21:52
If you have a lot of integration tests, you can setup an instance initializer and call `setLocale` from it for the time being so you don't have to call `setupIntl` in every module.

```
ember g instance-initializer intl
```

```js
// app/instance-initializers/intl.js

export function initialize(appInstance) {
  const intl = appInstance.lookup('service:intl');
  intl.setLocale('en-us');
}

export default {
  initialize,
};
```

**Comment by buschtoens** [comment] 2022-01-19 16:41
Only tangentially related, but please be advised, that there currently is a bit of confusion around the `v6.x` series and versioning in general. We're trying to resolve it soon. You can get more details in #1631.

Sorry for the trouble. 🙈

**Comment by ijlee2** [comment] 2023-09-19 15:12
I'll close the issue as the likely root cause has been identified (missing `setupIntl()` in integration tests that depend on `ember-intl`).

I've described the issue as a breaking change for `6.1.0` in the documentation.

**Closed by ijlee2** 2023-09-19 15:12 UTC
