### ISSUE TITLE
Custom outputPaths results in "Could not find module `@ember-intl/intl-relativeformat`"

### ISSUE THREAD

**Issue by jaurand** [ember-intl/ember-intl#804] opened 2019-02-26 00:52 UTC
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.13.3
- Ember CLI Version: 2.13.3
- Ember Intl Version: 3.5.0
- Browser(s): Chrome 72
- Node Version: 8.15
### Steps to Reproduce

In the ember-cli-build.js file of an app that uses ember-intl, set 
```
     outputPaths: {
        vendor: {
          js: '<somewhere else>'
```
To somewhere else.  (We output it to a Rails app assets/javascripts folder.)
Load app and see error
```
Error: Could not find module `@ember-intl/intl-relativeformat` imported from `ember-intl/services/intl`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:389)
    at Class.resolveOther (index.js:109)
    at Class.superWrapper [as resolveOther] (ember.debug.js:42856)
```

**Comment by jasonmit** [comment] 2019-02-26 04:28
I believe this is an upstream bug in ember-auto-import but was resolved in https://github.com/ef4/ember-auto-import/pull/107

Can you verify your package manager is pulling in the latest version of ember-auto-import.

**Comment by jaurand** [comment] 2019-02-26 14:26
`ember-auto-import` is listed as a dependency of `ember-intl` in our yarn.lock file as 1.2.13.  I believe that release is after that fix was merged.

**Comment by jasonmit** [comment] 2019-02-26 16:49
Can you put together a reproduction of the issue?

I cannot reproduce off of a brand new ember app and ember-intl install.

**Comment by jasonmit** [comment] 2019-02-26 19:16
> `ember-auto-import` is listed as a dependency of `ember-intl` in our yarn.lock file as 1.2.13. I believe that release is after that fix was merged.

The fix for this landed in 1.2.18 which is why you're running into the issue:
https://github.com/ef4/ember-auto-import/blob/master/CHANGELOG.md#1218

**Comment by zkrzyzanowski** [comment] 2019-03-11 15:03
Hi, I'm getting the same error in our app, with `ember-auto-import` in our lockfile at `1.2.19`

Ember Version: 3.8.0
Ember CLI Version: 3.8.1
Ember Intl Version: 3.5.2
Browser(s): Chrome 72
Node Version: 8

Let me know what other information you'd need. Thanks!

**Comment by jasonmit** [comment] 2019-03-11 17:35
@zkrzyzanowski can you reproduce it in a new ember app?  Does the issue go away when you nuke & recreate your lockfile?

**Comment by zkrzyzanowski** [comment] 2019-03-14 14:13
@jasonmit Thanks for the quick response, the issue still occurs after deleting & recreating the lockfile. I'll check if this can be reproduced in a new ember app today.

**Comment by jasonmit** [comment] 2019-03-14 18:20
@zkrzyzanowski strange that it's occurring after the lockfile was nuked.  I wasn't able to reproduce with a new ember app.  Any help to reproduce would be much appreciated :)

**Comment by jasonmit** [comment] 2019-04-02 21:04
Closing since no one has been able to reproduce it standalone.  If anyone can reproduce, please push the project somewhere and open a new issue.

**Closed by jasonmit** 2019-04-02 21:04 UTC
Labels: dependency issue, needs more information

**Comment by sandstrom** [comment] 2020-04-08 16:07
@zkrzyzanowski maybe this will solve your issue? https://github.com/ef4/ember-auto-import/issues/275
