### ISSUE TITLE
Incorrect versions/tags on NPM and docs site?

### ISSUE THREAD

**Issue by bertdeblock** [ember-intl/ember-intl#1631] opened 2022-01-03 08:53 UTC
AFAICT, `v6.0.0-beta.2` is currently the latest and greatest, though I'm a bit confused.
10 months ago, `v6.0.0` was published to NPM:
https://www.npmjs.com/package/ember-intl/v/6.0.0

And the docs site even includes `v6.0.1`:
https://ember-intl.github.io/ember-intl/versions/v6.0.1/

**Comment by longlho** [comment] 2022-01-04 05:49
Thanks for reporting! We'll take a look asap.

**Comment by gzurbach** [comment] 2022-01-18 11:58
@longlho Which version would you recommend installing as latest? `6.0.1`?

Thanks for your help!

**Comment by longlho** [comment] 2022-01-19 13:08
for now you can use the `6.0.0-beta.2` tag

**Comment by buschtoens** [comment] 2022-01-19 15:49
I did a bit of commit archaeology. Please don't take this as blaming. That's not the intention at all. If anything, I'm at least partly responsible for this. I'm only trying to clarify the history, so that we can finde the correct resolution. 💖

![image](https://user-images.githubusercontent.com/834636/150162533-602ef863-cfdd-42fb-92ef-1e44afcaa359.png)

- The last pre-confusion (😅) version was [`v5.6.2`](https://github.com/ember-intl/ember-intl/releases/tag/v5.6.2).
- Then major changes entered `main`, which couldn't be published in the `v5.x` series any more.
- These were then published by @longlho as `v6.0.0` and probably tagged as `latest` on npm, however the tag is missing on GitHub.
  - I suppose this should have been a `beta` instead, because of incompatibilities mentioned further down.
  - The version is currently still up on `npm`, but not tagged as `latest`.
- In the meantime @Turbo87 fixed an Ember deprecation via [`ddf97609`](https://github.com/ember-intl/ember-intl/commit/ddf97609e40b8d7283d2f43e528028581b03eb16) on an extra branch based off [`v5.6.2`](https://github.com/ember-intl/ember-intl/releases/tag/v5.6.2). This got published as [`v5.7.0`](https://github.com/ember-intl/ember-intl/releases/tag/v5.7.0), as `v6.0.0` wasn't ready yet.
- The changes were then [merged to `main`](https://github.com/ember-intl/ember-intl/commit/791a8c97fb9442cfe692fd80470d82ed2a1b646b) to not lose them with the `v6.0.0` release.
- https://github.com/ember-intl/ember-intl/issues/1564#issuecomment-876636821
  > Unfortunately, the `main` branch is in a broken state. The version got incremented to `6.0.0` and published as a `beta` after #1530 was merged. This PR introduced a `@dependentKeyCompat` decorator on `_locale` and AFACIT, this is one of the causes for the broken `main` branch. Nevertheless, I've published a `6.0.0-beta.1` with the latest (broken) state of `main`.
  >
  > I would rather invest time into stabilizing `6.0.0`, as it fixes this issue as a side-effect, than fixing it for `5.7.0` and pushing out an intermediary patch release.
- In the context of the above, I then accidentally publised `v6.0.1` on npm and subsequently unpublished it.
- I then published a first [`v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/releases/tag/v6.0.0-beta.1) with these changes: [`v5.6.2...v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/compare/v5.6.2...v6.0.0-beta.1)
- At this time, npm's `latest` tags should be:
  - `latest`: `v5.7.0`
  - `beta`: `v6.0.0-beta.1`
- Then three docs improvements and one dependency update were merged ([`v6.0.0-beta.1...v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/compare/v6.0.0-beta.1...v6.0.0-beta.2)), which @longlho published as [`v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/releases/tag/v6.0.0-beta.2).
- However as of now, npm's `beta` tag still points to `v6.0.0-beta.1`. It _should_ be `v6.0.0-beta.2`.
https://github.com/ember-intl/ember-intl/compare/v5.6.2...main
- Two further versions were published by @longlho: `v5.7.1` & `v5.7.2`, which is currently tagged as `latest` on npm.
  - However both are missing their tags on GitHub.
  - They _probably_ contain the most recent fix PRs:
    - #1609
    - #1607
    - #1616
  - They probably _also_ contain all the `v6.x` series changes.

@longlho Can you confirm this? Specifically the last bullet point?

**Comment by buschtoens** [comment] 2022-01-19 15:58
I think we need to do these things:

- Properly release `v6.x` and tag it as `latest` on npm, e.g. `v6.1.0`.
  - Are there any outstanding issues / incompatibilities that would prevent a proper `v6.x` release?
  - Do we want to include more breaking changes?
- Check wehther we should deprecate any versions from npm.
  - e.g. `v6.0.0`
  - If `v5.7.1` & `v5.7.2` indeed include `v6.x` breaking changes, we should consider deprecating them, once `v6.x` is released and tagged as `latest`.
    However, we must evaluate, whether by doing so we risk breaking apps of users who already upgraded to these versions vs. whether there's actually any real danger for users unwittingly installing these `v6.x` changes.
- To prevent future mistakes:
  - Create a `RELEASING.md`
  - Or even better yet, we could setup a fully automated releases process. @Turbo87 recently did this in one of my packages and AFAICT it's working really great: https://github.com/buschtoens/ember-link/pull/674

**Comment by buschtoens** [comment] 2022-01-19 23:19
I've (very crudely) created a few branches that show the diff between individual npm package versions by taking all files from `npm pack ember-intl@$VERSION` and checking them into the repo. Existing files are overridden with the `npm pack` version. Files absent from `npm pack`, but present in the repo are left untouched.

<details>
<summary>All branches and diffs</summary>

- [`diff-v5.6.2`](https://github.com/ember-intl/ember-intl/tree/diff-v5.6.2)
  - Based on [`v5.6.2`](https://github.com/ember-intl/ember-intl/releases/tag/v5.6.2).
  - [`v5.6.2...diff-v5.6.2`](https://github.com/ember-intl/ember-intl/compare/v5.6.2...diff-v5.6.2)
- [`diff-v5.7.0`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.0)
  - Based on [`diff-v5.6.2`](https://github.com/ember-intl/ember-intl/tree/diff-v5.6.2).
  - [`diff-v5.6.2...diff-v5.7.0`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v5.7.0)
- [`diff-v5.7.1`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.1)
  - Based on [`diff-v5.7.0`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.0).
  - [`diff-v5.7.0...diff-v5.7.1`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.0...diff-v5.7.1)
  - [`diff-v5.6.2...diff-v5.7.1`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v5.7.1)
- [`diff-v5.7.2`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.2)
  - Based on [`diff-v5.7.1`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.1).
  - [`diff-v5.7.1...diff-v5.7.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.1...diff-v5.7.2)
  - [`diff-v5.7.0...diff-v5.7.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.0...diff-v5.7.2)
  - [`diff-v5.6.2...diff-v5.7.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v5.7.2)
- [`diff-v6.0.0`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0)
  - Based on [`diff-v5.6.2`](https://github.com/ember-intl/ember-intl/tree/diff-v5.6.2).
  - [`diff-v5.6.2...diff-v6.0.0`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v6.0.0)
- [`diff-v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0-beta.1)
  - Based on [`diff-v6.0.0`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0).
  - [`diff-v6.0.0...diff-v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0...diff-v6.0.0-beta.1)
  - [`diff-v5.6.2...diff-v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v6.0.0-beta.1)
- [`diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0-beta.2)
  - Based on [`diff-v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0-beta.1).
  - [`diff-v6.0.0-beta.1...diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0-beta.1...diff-v6.0.0-beta.2)
  - [`diff-v6.0.0...diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0...diff-v6.0.0-beta.2)
  - [`diff-v5.6.2...diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v6.0.0-beta.2)
- [`diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0-beta.3)
  - Based on [`diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/tree/diff-v6.0.0-beta.2).
  - [`diff-v6.0.0-beta.2...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0-beta.2...diff-v6.0.0-beta.3)
  - [`diff-v6.0.0-beta.1...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0-beta.1...diff-v6.0.0-beta.3)
  - [`diff-v6.0.0...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0...diff-v6.0.0-beta.3)
  - [`diff-v5.6.2...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v6.0.0-beta.3)
- [`diff-v5.7.2-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.2-v6.0.0-beta.3)
  - Based on [`diff-v5.7.2`](https://github.com/ember-intl/ember-intl/tree/diff-v5.7.2).
  - [`diff-v5.7.2...diff-v5.7.2-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.2...diff-v5.7.2-v6.0.0-beta.3)

</details>

Based on these diffs I've tried to re-construct a changelog:

<details>
<summary>Changelog</summary>

### `v6.0.0`

[`diff-v5.6.2...diff-v6.0.0`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v6.0.0)

_individual commits not easily tracebable or not in `main` history_

### `v5.7.0`

[`diff-v5.6.2...diff-v5.7.0`](https://github.com/ember-intl/ember-intl/compare/diff-v5.6.2...diff-v5.7.0)

- #1515
- #1518
- #1519
- #1517
- ddf97609e40b8d7283d2f43e528028581b03eb16

### `v6.0.0-beta.1`

[`diff-v6.0.0...diff-v6.0.0-beta.1`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0...diff-v6.0.0-beta.1)

_individual commits not easily tracebable or not in `main` history_

### `v6.0.0-beta.2`

[`diff-v6.0.0-beta.1...diff-v6.0.0-beta.2`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0-beta.1...diff-v6.0.0-beta.2)

- #1586
- (#1597)
- #1599

### `v6.0.0-beta.3`

[`diff-v6.0.0-beta.2...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0-beta.2...diff-v6.0.0-beta.3)

- #1607
- #1616
- #1633

### `v5.7.1`

[`diff-v5.7.0...diff-v5.7.1`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.0...diff-v5.7.1)

_individual commits not easily tracebable or not in `main` history_

### `v5.7.2`

[`diff-v5.7.1...diff-v5.7.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.1...diff-v5.7.2)

No changes.

</details>

The following diffs are primarily relevant for deciding the next steps:

- [`diff-v5.7.0...diff-v5.7.2`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.0...diff-v5.7.2)
  - `v5.7.0`: Last version where all changes are certainly known.
  - `v5.7.2`: Current `latest` on npm, where the changes are unknown.
- [`diff-v5.7.2...diff-v5.7.2-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v5.7.2...diff-v5.7.2-v6.0.0-beta.3)
  - `v5.7.2`: Current `latest` on npm, where the changes are unknown.
  - `v6.0.0-beta.3`: Current `beta` on npm and idetical to current `main` branch. All changes are known.
  - Further `v6.x` development will be based on this, therefore this will be the future upgrade path from `v5.x` to the _proper_ `v6.x`.
- [`diff-v6.0.0...diff-v6.0.0-beta.3`](https://github.com/ember-intl/ember-intl/compare/diff-v6.0.0...diff-v6.0.0-beta.3)
  - `v6.0.0`: Supposedly accidentally published version, still live on npm. Specific changes unknown.
  - `v6.0.0-beta.3`: Current `beta` on npm and idetical to current `main` branch. All changes are known.
  - Further `v6.x` development will be based on this, therefore this will be the future upgrade path from `v6.0.0` to the _proper_ `v6.x` release.

**Comment by buschtoens** [comment] 2022-01-20 07:07
FWIW I've started #1634, which seeks to repair CI for newer Ember `v4.x` versions.

One of the biggest blockers / problems is that `ember-intl` still uses the unmaintained and broken `ember-cli-addon-docs`. We should replace it.

Locally I can get it to build again, but in CI it's dying with segfaults. Probably we need to update some more build time dependencies.

I would suggest that once the PR is passing CI, we evaluate how far down we can and want to support old Ember versions. This would then also be a good opportunity to cut another / proper `v7.x` major release, as we're dropping support. This means that we can also leave all this `v5.x` / `v6.x` mess behind us.

**Comment by gzurbach** [comment] 2022-01-20 07:34
@buschtoens Thank you for looking into this and sending all these details. I don't think I have the skills to help, but I'm impressed and supportive of your efforts to fix this 👍

**Comment by longlho** [comment] 2022-01-20 18:18
@buschtoens looking at 6.x download stat I think it's fine to release as 6.x w/o bumping to 7.x

**Comment by buschtoens** [comment] 2022-01-20 20:27
@longlho Fine with me. 👌

Do you maybe have any recollection of what changes specifically went into `v5.7.1` / `v5.7.2`, when compared to `v5.7.0`? I would like to backport a few fixes for `v5.x`, but I'm unsure, what commit / tag / branch to base my backport on.

**Comment by runspired** [comment] 2022-03-11 19:13
Is there a changelog anywhere for what to expect in v6?

**Comment by gzurbach** [comment] 2022-03-16 09:51
@buschtoens Any update on this? Seems like you've spent a significant amount of time understanding the mess that occurred in this repo's versions/tags. Is there anything we can do to help you untangle this? `ember-intl` is a key library of our app so if you need help for testing/debugging etc. let us know!

**Comment by ijlee2** [comment] 2023-09-19 15:15
@bertdeblock and others:

As it has been noted, `6.0.0` had been released by accident and is not a stable version.

I'll close this issue now, because `6.1.0` will be released soon and will mark the beginning of the `6.x` series.

**Closed by ijlee2** 2023-09-19 15:15 UTC

**Comment by bertdeblock** [comment] 2023-09-19 15:31
Could you maybe deprecate v6.0.0 specifically on npm and remove [v6.0.1](https://ember-intl.github.io/ember-intl/versions/v6.0.1) from the docs?

**Comment by ijlee2** [comment] 2023-09-19 15:50
Hmm. On `npm`, I only see the option to mark all versions of the package as deprecated.

<img width="800" alt="" src="https://github.com/ember-intl/ember-intl/assets/16869656/462492f4-cab0-4d31-83c9-ffefd13d411c">

Do you know we can deprecate just 1 version and remove `6.0.1` from the docs? (I don't use `ember-cli-addon-docs` outside of this repo, so I'm not sure if I can just remove the corresponding branch/tag.)

If there isn't an easy way, I think it's okay to leave these around. I indicated in the changelog, release notes, and migration guide in the documentation that `6.0.0` is not a stable release.
