### ISSUE TITLE
Rendering tests fail with get before set during rendering inside ember-intl

### ISSUE THREAD

**Issue by lupestro** [ember-intl/ember-intl#1750] opened 2023-04-28 00:14 UTC
- [X] I am NOT on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version

No, I’m on 6.0-beta-4. The failure does not occur on 5.x.

- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 4.8
- Ember CLI Version: 4.8
- Ember Intl Version: 6.0-beta-4
- Browser(s): tested with Chrome but not browser specific
- Node Version: I tried it on 16, but it shouldn’t matter.

### Steps to Reproduce

* Create a rendering test with an hbs`<some-component-that-uses-intl/>`
* Do not make any reference to ember-intl before the hbs, so that the ember-intl service is constructed during rendering.

The constructor does a get to the this.locale tracked property and later does a set to the same property. Big error in the console and the test fails.

Workaround: place a setupIntl(hooks) in the setupRenderingTest(hooks) wrapper. 

The workaround is a reasonable thing to do anyway, but the error did not occur in 5.x. At the very least, the requirement to call setupIntl() on rendering tests should be marked as a breaking change.

This is almost never a problem for running apps or application tests because any application that uses ember-intl will be doing some setup early, typically in the application route model hook and thus the service will be constructed before anything tries to render. It also won’t be a test for unit tests because they don’t use Glimmer to render anything.

**Comment by ijlee2** [comment] 2023-09-19 15:23
I'll close the issue as the likely root cause has been identified (missing `setupIntl()` in integration tests that depend on `ember-intl`).

I've described the issue as a breaking change for `6.1.0` in the documentation.

Related issues: #1611 and #1659

**Closed by ijlee2** 2023-09-19 15:23 UTC
