### ISSUE TITLE
IE 11 error : Could not find module `@ember-intl/intl-relativeformat` imported from `ember-intl/services/intl

### ISSUE THREAD

**Issue by lakshmiJain** [ember-intl/ember-intl#1478] opened 2020-12-17 14:05 UTC
- [No ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [Not a duplicate ] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.2.0
- Ember CLI Version: 3.2.0
- Ember Intl Version: 4.3.1
- Browser(s): IE 11
- Node Version: 8

### Steps to Reproduce

Was working till yesterday. The same application breaking in IE 11 with this error in console -
Could not find module `@ember-intl/intl-relativeformat` imported from `ember-intl/services/intl.

Any solutions/thoughts are highly appreciated. Thanks

**Comment by buschtoens** [comment] 2020-12-17 14:41
> Was working till yesterday.

Well, what changed? 😄 

We dropped the `@ember-intl/intl-relativeformat` polyfill with `ember-intl@5`. It seems like you are accidentally depending on `ember-intl@4` somewhere and it's clobbering your `@5` version. I can highly suggest installing [`ember-cli-dependency-lint`](https://github.com/salsify/ember-cli-dependency-lint), to detect such issues.

**Comment by lakshmiJain** [comment] 2020-12-17 15:23
Thanks for your quick response.

well nothing changed. that's strange.
Thanks for your suggestion, trying that now.
I am not using @5 version as of now.

Would @ember-intl/intl-relativeformat polyfill  cause issues with @4 version too ?

**Comment by buschtoens** [comment] 2020-12-17 15:32
> I am not using @5 version as of now.

Oh yeah! I misread your OP, sorry.

This issue is probably a dupe of #804. You probably have some an outdated `ember-auto-import` version clobbering over the latest one.

Are you using `yarn`? You could try setting a resolution for the latest `ember-auto-import`.

**Comment by ankitmadhwani24** [comment] 2020-12-22 04:46
I am also facing the same issue with INTL version 4.3.1.
also tried an updated version of ember-auto-import. but no luck

**Comment by sandstrom** [comment] 2021-06-02 10:45
If this is an IE only error I'd suggest not spending any time on it. 

IE is quickly on it's way out and there are more important things to work on in ember-intl.

**Comment by sandstrom** [comment] 2022-09-01 18:50
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by ijlee2** [comment] 2023-09-19 15:09
Will close this issue as Ember doesn't support IE 11.

**Closed by ijlee2** 2023-09-19 15:09 UTC
