### ISSUE TITLE
Source map error

### ISSUE THREAD

**Issue by wukongrita** [ember-intl/ember-intl#880] opened 2019-05-22 04:28 UTC
Hi, I am using Firefox 67 (64 bit) and getting this message:

```
    DEBUG: ------------------------------- index.js:185
    DEBUG: Ember             : 3.8.1 index.js:185
    DEBUG: Ember Data        : 3.8.0 index.js:185
    DEBUG: jQuery            : 3.4.1 index.js:185
    DEBUG: Ember Paper       : 1.0.0-beta.24 index.js:185
    DEBUG: Ember Simple Auth : 1.8.2 index.js:185
    DEBUG: ------------------------------- index.js:185
    Source map error: TypeError: main.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-relativeformat/lib/main.js?
    Source Map URL: main.js.map[Learn More]
    Source map error: TypeError: core.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-relativeformat/lib/core.js?
    Source Map URL: core.js.map[Learn More]
    Source map error: TypeError: main.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/main.js?
    Source Map URL: main.js.map[Learn More]
    Source map error: TypeError: core.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/core.js?
    Source Map URL: core.js.map[Learn More]
    Source map error: TypeError: utils.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/utils.js?
    Source Map URL: utils.js.map[Learn More]
    Source map error: TypeError: es5.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/es5.js?
    Source Map URL: es5.js.map[Learn More]
    Source map error: TypeError: compiler.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/compiler.js?
    Source Map URL: compiler.js.map[Learn More]
    Source map error: TypeError: parser.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat-parser/lib/parser.js?
    Source Map URL: parser.js.map[Learn More]
    Source map error: TypeError: en.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-messageformat/lib/en.js?
    Source Map URL: en.js.map[Learn More]
    Source map error: TypeError: diff.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-relativeformat/lib/diff.js?
    Source Map URL: diff.js.map[Learn More]
    Source map error: TypeError: es5.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-relativeformat/lib/es5.js?
    Source Map URL: es5.js.map[Learn More]
    Source map error: TypeError: en.js.map is not a valid URL.
    Resource URL: webpack://__ember_auto_import__/./node_modules/@ember-intl/intl-relativeformat/lib/en.js?
    Source Map URL: en.js.map[Learn More]
```

### Environment

- Ember Version: 3.8.1
- Ember CLI Version: 3.8.1
- Ember Intl Version: 3.5.2,
- Browser(s): Firefox 67 (64 bit)
- Node Version:  8.9.4

any help how to  solve this? thanks...

**Comment by jasonmit** [comment] 2019-05-31 01:36
Is anyone else able to reproduce this?  If not, can you provide a reproduction?

**Comment by jasonmit** [comment] 2019-05-31 01:38
Seems related to https://github.com/ef4/ember-auto-import/issues/124#issuecomment-421321063 but solved but bumping deps.  In your case, may need to rebuild a portion of your lockfile.

**Comment by jnicklas** [comment] 2019-06-03 15:35
I'm also seeing these errors on Firefox 67, neither Chrome nor Safari show the same error against the same app, so this seems to be something specific to Firefox. Sorry I don't have time to investigate this further right now, but maybe that little bit helps.

**Comment by jnicklas** [comment] 2019-06-07 14:08
Weirdly, these errors have now disappeared for me on Firefox 67.0.1, maybe this was a bug in FF? At any rate it seems to be fixed now, for me at least. 🤷‍♂️

**Comment by jasonmit** [comment] 2019-10-21 00:03
Is this still an issue after bumping ember-auto-import in your lockfile?

**Comment by jasonmit** [comment] 2019-10-23 19:44
Feel free to open a new issue with steps to reproduce if this continues on latest stable.

**Closed by jasonmit** 2019-10-23 19:44 UTC
Labels: needs verification
